### PR TITLE
Fixed search issue and pagination issue

### LINKED ISSUE #27: Search results are very fuzzy
Limit the fuzziness of search results to 0.5 or less to make the search results more relevant.

cc: @nihal467 @developedBySJ

### LINKED ISSUE #28: Pagination malfunction
When filtered although we have only 3 results, the pagination is showing the metadata before filtering
image
 
cc: @nihal467 @developedBySJ

### LINKED ISSUE #29: Add tooltips to ambiguous data
In the cards, the data we show seems to be ambiguous (hard to understand), so add a tooltip to show what we are showing

image
In the above image, it is hard to understand what the patient discharged is showing

cc: @nihal467 @developedBySJ

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #27 
Fixes #28 
Fixes #29

### CODE REVIEW

File: src/components/tooltip.tsx [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+  className?: string
+  text: ReactNode
+  position?: 'TOP' | 'BOTTOM' | 'LEFT' | 'RIGHT'
+}) {
+  const { position = 'TOP', className = '' } = props
+
+  const [status, show] = useState(false)
+
+  const style = clsx(
+    'absolute bg-black/50 backdrop-blur rounded text-white transition px-2 py-1 z-50 w-fit text-center block',
```
Comment (developedBySJ) [inline src/components/tooltip.tsx:15]: Prefer `slate-grey` for the background to match the theme

File: src/pages/district/Capacity.tsx [hunk 2]
```diff
@@ -66,11 +66,15 @@ export default function Capacity({ districtName }: Props) {
...
-    searchValue,
-  })
+  const { handlePageChange, page, paginatedData, totalPage, totalResults } =
+    usePaginateData({
+      data: tableData,
+      keys: ['facility_name'],
+      searchValue,
+    })
+
+  console.log(paginatedData)
```
Comment (developedBySJ) [inline src/pages/district/Capacity.tsx:76]: Remove log

File: src/utils/hooks/usePaginateData.ts [hunk 3]
```diff
@@ -11,35 +11,49 @@ interface UsePaginationDataArgs<T> {
...
+    let newData = data
     if (searchValue.length) {
-      const newData = fuseData.current.search(searchValue).map((i) => i.item)
-      setPaginatedData(newData.slice(0, 10))
-    } else {
-      setPaginatedData(data.slice(skip, end))
+      newData = fuseData.current
+        .search({ facility_name: searchValue })
+        .filter((i) => (i?.score || 0) <= 0.5)
+        .map((i) => i.item)
```
Comment (developedBySJ) [inline src/utils/hooks/usePaginateData.ts:39]: Use [threshold](https://fusejs.io/api/options.html#threshold) option instead if manual filtering

File: src/utils/hooks/usePaginateData.ts [hunk 4]
```diff
@@ -11,35 +11,49 @@ interface UsePaginationDataArgs<T> {
...
+    keys,
+    searchValue,
+    resultsPerPage = DEFAULT_RESULTS_PER_PAGE,
+  } = args
 
-  const fuseData = useRef(new Fuse(data, { keys }))
+  const fuseData = useRef(new Fuse(data, { keys, includeScore: true }))
 
   const [page, setPage] = useState(1)
+  const [totalPage, setTotalPage] = useState(
```
Comment (developedBySJ) [inline src/utils/hooks/usePaginateData.ts:24]: Why is this state required?

**Review by developedBySJ — CHANGES_REQUESTED** [review]
There is a bug when you don't have any data and you click on the last page button
image

can you add an empty state (something like `No facility found`)?

File: src/components/tooltip.tsx (hunk 1 above)
Comment (khavinshankar) [reply src/components/tooltip.tsx:15]: The cards are already stale-grey, so using it would make it the same as existing background

File: src/utils/hooks/usePaginateData.ts (hunk 4 above)
Comment (khavinshankar) [reply src/utils/hooks/usePaginateData.ts:24]: That was intentional because there was a weird state error with page, so adding that resolved it
